### PR TITLE
Persist console messages across reconnects

### PR DESCRIPTION
**Pull request by jkrems**
A different approach to https://github.com/buggerjs/bugger/pull/57.

@caspervonb Does this address your problem?

### CODE REVIEW

**Comment by caspervonb** [comment]
:+1: LGTM

**Comment by caspervonb** [comment]
Actually, the buffer needs to be cleared on enable. Only messages up until enable is called should be buffered.

**Comment by caspervonb** [comment]
Chrome treats any console.enable calls after the console has been enabled as no-ops. With this PR each `console.enable` call will deliver all the tracked console messages each time enable is called.

Console.enable should only deliver the messages tracked between the time of being disabled (The initial state being disabled), and the time of being enabled.

Could do this by storing an offset in the agent if the same agent used throughout the lifetime of the process.

**Comment by jkrems** [comment]
Guess this means creating agent instances per connection. I checked the Blink code and Chrome does the same this PR does (it sends *all* Console messages during the lifetime so far) but it tracks the enabled state of the agent and does an early return if enable has been called already. In other words: for a well-behaved client (which doesn't "randomly" call enable multiple times), this PR's and Chrome's behavior are the same. Buffering the messages will cause the wrong behavior when calling disable and then enable. Which should cause a full resend of all messages afaict.

Will do the switch to per-connection agents in a separate PR.

**Pull request merged**
